### ISSUE TITLE
Which Face Model?

### ISSUE THREAD

**Issue by emlcpfx** [XiangyuZhu-open/Beyond3DMM#10]
Which face model is this using? Does it need a commercial license, or is it open source?

**Comment by XiangyuZhu-open** [comment]
We use the Basel Face Model, which is the same as 3DDFA, https://github.com/cleardusk/3DDFA

**Comment by emlcpfx** [comment]
Is it possible to use the FLAME model instead, so it could be used commercially without incurring licensing fees?

**Comment by XiangyuZhu-open** [comment]
It is possible, but the code would require significant reimplementation.

**Comment by emlcpfx** [comment]
Thank you for answering!!
